version: "3"
services:
  db:
    image: mysql:latest
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    env_file:
      - ./.env
    environment:
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_PASSWORD=$DB_PASSWORD
      - TZ=Asia/Tokyo
    ports:
      - "4306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  pictweet-go:
    stdin_open: true
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    environment:
      - DB_USERNAME=$DB_USERNAME
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_DATABASE=$DB_DATABASE
      - KEY_JSON_PATH=$KEY_JSON_PATH
      - PROJECT_ID=$PROJECT_ID
      - PORT=$PORT
      - REVERSE_PROXY_PORT=$REVERSE_PROXY_PORT
    ports:
      - "8080:8080"

volumes:
  dbdata:
