version: "3.7"
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USERNAME
      TZ: 'Asia/Tokyo'
  pictweet-go:
    stdin_open: true
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    environment:
      - DB_USERNAME=$DB_USERNAME
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_DATABASE=$DB_DATABASE
      - KEY_JSON_PATH=$KEY_JSON_PATH
      - PROJECT_ID=$PROJECT_ID
      - PORT=$PORT
      - REVERSE_PROXY_PORT=$REVERSE_PROXY_PORT
    ports:
      - "8080:8080"

