// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/interfaces/rpc/pictweetpb/pictweet.proto

package pictweetpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Tweet struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ImageUrl             string   `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Author               string   `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,6,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	CreatedAt            string   `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tweet) Reset()         { *m = Tweet{} }
func (m *Tweet) String() string { return proto.CompactTextString(m) }
func (*Tweet) ProtoMessage()    {}
func (*Tweet) Descriptor() ([]byte, []int) {
	return fileDescriptor_68340c3d12cfe5fb, []int{0}
}

func (m *Tweet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tweet.Unmarshal(m, b)
}
func (m *Tweet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tweet.Marshal(b, m, deterministic)
}
func (m *Tweet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tweet.Merge(m, src)
}
func (m *Tweet) XXX_Size() int {
	return xxx_messageInfo_Tweet.Size(m)
}
func (m *Tweet) XXX_DiscardUnknown() {
	xxx_messageInfo_Tweet.DiscardUnknown(m)
}

var xxx_messageInfo_Tweet proto.InternalMessageInfo

func (m *Tweet) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Tweet) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Tweet) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Tweet) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *Tweet) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Tweet) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *Tweet) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type Comment struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	UserId               int32    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt            string   `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_68340c3d12cfe5fb, []int{1}
}

func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (m *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(m, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Comment) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Comment) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Comment) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type ListTweetsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTweetsRequest) Reset()         { *m = ListTweetsRequest{} }
func (m *ListTweetsRequest) String() string { return proto.CompactTextString(m) }
func (*ListTweetsRequest) ProtoMessage()    {}
func (*ListTweetsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68340c3d12cfe5fb, []int{2}
}

func (m *ListTweetsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTweetsRequest.Unmarshal(m, b)
}
func (m *ListTweetsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTweetsRequest.Marshal(b, m, deterministic)
}
func (m *ListTweetsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTweetsRequest.Merge(m, src)
}
func (m *ListTweetsRequest) XXX_Size() int {
	return xxx_messageInfo_ListTweetsRequest.Size(m)
}
func (m *ListTweetsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTweetsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTweetsRequest proto.InternalMessageInfo

type ListTweetsResponse struct {
	Tweet                []*Tweet `protobuf:"bytes,1,rep,name=tweet,proto3" json:"tweet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTweetsResponse) Reset()         { *m = ListTweetsResponse{} }
func (m *ListTweetsResponse) String() string { return proto.CompactTextString(m) }
func (*ListTweetsResponse) ProtoMessage()    {}
func (*ListTweetsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68340c3d12cfe5fb, []int{3}
}

func (m *ListTweetsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTweetsResponse.Unmarshal(m, b)
}
func (m *ListTweetsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTweetsResponse.Marshal(b, m, deterministic)
}
func (m *ListTweetsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTweetsResponse.Merge(m, src)
}
func (m *ListTweetsResponse) XXX_Size() int {
	return xxx_messageInfo_ListTweetsResponse.Size(m)
}
func (m *ListTweetsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTweetsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTweetsResponse proto.InternalMessageInfo

func (m *ListTweetsResponse) GetTweet() []*Tweet {
	if m != nil {
		return m.Tweet
	}
	return nil
}

type PostTweetRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ImageUrl             string   `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	UserId               int32    `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostTweetRequest) Reset()         { *m = PostTweetRequest{} }
func (m *PostTweetRequest) String() string { return proto.CompactTextString(m) }
func (*PostTweetRequest) ProtoMessage()    {}
func (*PostTweetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68340c3d12cfe5fb, []int{4}
}

func (m *PostTweetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostTweetRequest.Unmarshal(m, b)
}
func (m *PostTweetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostTweetRequest.Marshal(b, m, deterministic)
}
func (m *PostTweetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostTweetRequest.Merge(m, src)
}
func (m *PostTweetRequest) XXX_Size() int {
	return xxx_messageInfo_PostTweetRequest.Size(m)
}
func (m *PostTweetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostTweetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostTweetRequest proto.InternalMessageInfo

func (m *PostTweetRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PostTweetRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PostTweetRequest) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *PostTweetRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type PostTweetResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostTweetResponse) Reset()         { *m = PostTweetResponse{} }
func (m *PostTweetResponse) String() string { return proto.CompactTextString(m) }
func (*PostTweetResponse) ProtoMessage()    {}
func (*PostTweetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68340c3d12cfe5fb, []int{5}
}

func (m *PostTweetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostTweetResponse.Unmarshal(m, b)
}
func (m *PostTweetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostTweetResponse.Marshal(b, m, deterministic)
}
func (m *PostTweetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostTweetResponse.Merge(m, src)
}
func (m *PostTweetResponse) XXX_Size() int {
	return xxx_messageInfo_PostTweetResponse.Size(m)
}
func (m *PostTweetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostTweetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostTweetResponse proto.InternalMessageInfo

func (m *PostTweetResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type ShowTweetRequest struct {
	TweetId              int32    `protobuf:"varint,1,opt,name=tweet_id,json=tweetId,proto3" json:"tweet_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowTweetRequest) Reset()         { *m = ShowTweetRequest{} }
func (m *ShowTweetRequest) String() string { return proto.CompactTextString(m) }
func (*ShowTweetRequest) ProtoMessage()    {}
func (*ShowTweetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68340c3d12cfe5fb, []int{6}
}

func (m *ShowTweetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowTweetRequest.Unmarshal(m, b)
}
func (m *ShowTweetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowTweetRequest.Marshal(b, m, deterministic)
}
func (m *ShowTweetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowTweetRequest.Merge(m, src)
}
func (m *ShowTweetRequest) XXX_Size() int {
	return xxx_messageInfo_ShowTweetRequest.Size(m)
}
func (m *ShowTweetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowTweetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShowTweetRequest proto.InternalMessageInfo

func (m *ShowTweetRequest) GetTweetId() int32 {
	if m != nil {
		return m.TweetId
	}
	return 0
}

type ShowTweetResponse struct {
	Tweet                *Tweet     `protobuf:"bytes,1,opt,name=tweet,proto3" json:"tweet,omitempty"`
	Comment              []*Comment `protobuf:"bytes,2,rep,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ShowTweetResponse) Reset()         { *m = ShowTweetResponse{} }
func (m *ShowTweetResponse) String() string { return proto.CompactTextString(m) }
func (*ShowTweetResponse) ProtoMessage()    {}
func (*ShowTweetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68340c3d12cfe5fb, []int{7}
}

func (m *ShowTweetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowTweetResponse.Unmarshal(m, b)
}
func (m *ShowTweetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowTweetResponse.Marshal(b, m, deterministic)
}
func (m *ShowTweetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowTweetResponse.Merge(m, src)
}
func (m *ShowTweetResponse) XXX_Size() int {
	return xxx_messageInfo_ShowTweetResponse.Size(m)
}
func (m *ShowTweetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowTweetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShowTweetResponse proto.InternalMessageInfo

func (m *ShowTweetResponse) GetTweet() *Tweet {
	if m != nil {
		return m.Tweet
	}
	return nil
}

func (m *ShowTweetResponse) GetComment() []*Comment {
	if m != nil {
		return m.Comment
	}
	return nil
}

type PostCommentRequest struct {
	TweetId              int32    `protobuf:"varint,1,opt,name=tweet_id,json=tweetId,proto3" json:"tweet_id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostCommentRequest) Reset()         { *m = PostCommentRequest{} }
func (m *PostCommentRequest) String() string { return proto.CompactTextString(m) }
func (*PostCommentRequest) ProtoMessage()    {}
func (*PostCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68340c3d12cfe5fb, []int{8}
}

func (m *PostCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostCommentRequest.Unmarshal(m, b)
}
func (m *PostCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostCommentRequest.Marshal(b, m, deterministic)
}
func (m *PostCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostCommentRequest.Merge(m, src)
}
func (m *PostCommentRequest) XXX_Size() int {
	return xxx_messageInfo_PostCommentRequest.Size(m)
}
func (m *PostCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostCommentRequest proto.InternalMessageInfo

func (m *PostCommentRequest) GetTweetId() int32 {
	if m != nil {
		return m.TweetId
	}
	return 0
}

func (m *PostCommentRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PostCommentRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type PostCommentResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostCommentResponse) Reset()         { *m = PostCommentResponse{} }
func (m *PostCommentResponse) String() string { return proto.CompactTextString(m) }
func (*PostCommentResponse) ProtoMessage()    {}
func (*PostCommentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68340c3d12cfe5fb, []int{9}
}

func (m *PostCommentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostCommentResponse.Unmarshal(m, b)
}
func (m *PostCommentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostCommentResponse.Marshal(b, m, deterministic)
}
func (m *PostCommentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostCommentResponse.Merge(m, src)
}
func (m *PostCommentResponse) XXX_Size() int {
	return xxx_messageInfo_PostCommentResponse.Size(m)
}
func (m *PostCommentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostCommentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostCommentResponse proto.InternalMessageInfo

func (m *PostCommentResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type DeleteTweetRequest struct {
	TweetId              int32    `protobuf:"varint,1,opt,name=tweet_id,json=tweetId,proto3" json:"tweet_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTweetRequest) Reset()         { *m = DeleteTweetRequest{} }
func (m *DeleteTweetRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTweetRequest) ProtoMessage()    {}
func (*DeleteTweetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68340c3d12cfe5fb, []int{10}
}

func (m *DeleteTweetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTweetRequest.Unmarshal(m, b)
}
func (m *DeleteTweetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTweetRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTweetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTweetRequest.Merge(m, src)
}
func (m *DeleteTweetRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTweetRequest.Size(m)
}
func (m *DeleteTweetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTweetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTweetRequest proto.InternalMessageInfo

func (m *DeleteTweetRequest) GetTweetId() int32 {
	if m != nil {
		return m.TweetId
	}
	return 0
}

type DeleteTweetResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTweetResponse) Reset()         { *m = DeleteTweetResponse{} }
func (m *DeleteTweetResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTweetResponse) ProtoMessage()    {}
func (*DeleteTweetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68340c3d12cfe5fb, []int{11}
}

func (m *DeleteTweetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTweetResponse.Unmarshal(m, b)
}
func (m *DeleteTweetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTweetResponse.Marshal(b, m, deterministic)
}
func (m *DeleteTweetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTweetResponse.Merge(m, src)
}
func (m *DeleteTweetResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteTweetResponse.Size(m)
}
func (m *DeleteTweetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTweetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTweetResponse proto.InternalMessageInfo

func (m *DeleteTweetResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type RegisterUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserRequest) Reset()         { *m = RegisterUserRequest{} }
func (m *RegisterUserRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterUserRequest) ProtoMessage()    {}
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68340c3d12cfe5fb, []int{12}
}

func (m *RegisterUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserRequest.Unmarshal(m, b)
}
func (m *RegisterUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserRequest.Marshal(b, m, deterministic)
}
func (m *RegisterUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserRequest.Merge(m, src)
}
func (m *RegisterUserRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterUserRequest.Size(m)
}
func (m *RegisterUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserRequest proto.InternalMessageInfo

func (m *RegisterUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterUserRequest) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

type RegsiterUserResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegsiterUserResponse) Reset()         { *m = RegsiterUserResponse{} }
func (m *RegsiterUserResponse) String() string { return proto.CompactTextString(m) }
func (*RegsiterUserResponse) ProtoMessage()    {}
func (*RegsiterUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68340c3d12cfe5fb, []int{13}
}

func (m *RegsiterUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegsiterUserResponse.Unmarshal(m, b)
}
func (m *RegsiterUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegsiterUserResponse.Marshal(b, m, deterministic)
}
func (m *RegsiterUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegsiterUserResponse.Merge(m, src)
}
func (m *RegsiterUserResponse) XXX_Size() int {
	return xxx_messageInfo_RegsiterUserResponse.Size(m)
}
func (m *RegsiterUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegsiterUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegsiterUserResponse proto.InternalMessageInfo

func (m *RegsiterUserResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Tweet)(nil), "pictweet.Tweet")
	proto.RegisterType((*Comment)(nil), "pictweet.Comment")
	proto.RegisterType((*ListTweetsRequest)(nil), "pictweet.ListTweetsRequest")
	proto.RegisterType((*ListTweetsResponse)(nil), "pictweet.ListTweetsResponse")
	proto.RegisterType((*PostTweetRequest)(nil), "pictweet.PostTweetRequest")
	proto.RegisterType((*PostTweetResponse)(nil), "pictweet.PostTweetResponse")
	proto.RegisterType((*ShowTweetRequest)(nil), "pictweet.ShowTweetRequest")
	proto.RegisterType((*ShowTweetResponse)(nil), "pictweet.ShowTweetResponse")
	proto.RegisterType((*PostCommentRequest)(nil), "pictweet.PostCommentRequest")
	proto.RegisterType((*PostCommentResponse)(nil), "pictweet.PostCommentResponse")
	proto.RegisterType((*DeleteTweetRequest)(nil), "pictweet.DeleteTweetRequest")
	proto.RegisterType((*DeleteTweetResponse)(nil), "pictweet.DeleteTweetResponse")
	proto.RegisterType((*RegisterUserRequest)(nil), "pictweet.RegisterUserRequest")
	proto.RegisterType((*RegsiterUserResponse)(nil), "pictweet.RegsiterUserResponse")
}

func init() {
	proto.RegisterFile("src/interfaces/rpc/pictweetpb/pictweet.proto", fileDescriptor_68340c3d12cfe5fb)
}

var fileDescriptor_68340c3d12cfe5fb = []byte{
	// 602 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x6d, 0x6b, 0xdb, 0x30,
	0x10, 0x8e, 0x9d, 0x38, 0x69, 0xae, 0x65, 0x6d, 0x94, 0xd2, 0x79, 0x49, 0x33, 0x82, 0x60, 0x10,
	0xe8, 0x92, 0x40, 0xf7, 0x71, 0x9f, 0xf6, 0xc2, 0x20, 0x50, 0x58, 0x71, 0x57, 0x06, 0x63, 0x10,
	0x5c, 0xfb, 0x96, 0x0a, 0x9c, 0x38, 0x93, 0x94, 0xb6, 0xbf, 0x6d, 0xff, 0x64, 0xff, 0x66, 0x58,
	0x91, 0x6d, 0xd9, 0x49, 0x9a, 0x7d, 0xd3, 0xdd, 0x49, 0xcf, 0xdd, 0x3d, 0xf7, 0x1c, 0x82, 0xb7,
	0x82, 0x07, 0x63, 0xb6, 0x90, 0xc8, 0x7f, 0xf9, 0x01, 0x8a, 0x31, 0x5f, 0x06, 0xe3, 0x25, 0x0b,
	0xe4, 0x23, 0xa2, 0x5c, 0xde, 0x65, 0xc7, 0xd1, 0x92, 0xc7, 0x32, 0x26, 0x07, 0xa9, 0x4d, 0xff,
	0x58, 0xe0, 0x7c, 0x4b, 0x4e, 0xe4, 0x05, 0xd8, 0x2c, 0x74, 0xad, 0xbe, 0x35, 0x70, 0x3c, 0x9b,
	0x85, 0xe4, 0x14, 0x1c, 0xc9, 0x64, 0x84, 0xae, 0xdd, 0xb7, 0x06, 0x4d, 0x6f, 0x6d, 0x10, 0x17,
	0x1a, 0x41, 0xbc, 0x90, 0xb8, 0x90, 0x6e, 0x55, 0xf9, 0x53, 0x93, 0x74, 0xa1, 0xc9, 0xe6, 0xfe,
	0x0c, 0xa7, 0x2b, 0x1e, 0xb9, 0x35, 0x15, 0x3b, 0x50, 0x8e, 0x5b, 0x1e, 0x91, 0x33, 0xa8, 0xfb,
	0x2b, 0x79, 0x1f, 0x73, 0xd7, 0x51, 0x11, 0x6d, 0x91, 0x1e, 0x80, 0xff, 0xe0, 0x4b, 0x9f, 0xab,
	0x57, 0x75, 0x15, 0x6b, 0xae, 0x3d, 0xc9, 0xb3, 0x1e, 0x40, 0xc0, 0xd1, 0x97, 0x18, 0x4e, 0x7d,
	0xe9, 0x36, 0xd6, 0x61, 0xed, 0xf9, 0x20, 0x29, 0x42, 0xe3, 0x53, 0x3c, 0x9f, 0x27, 0xd9, 0xcb,
	0xd5, 0x13, 0xa8, 0x49, 0x7c, 0x92, 0xba, 0x78, 0x75, 0x26, 0x2f, 0xa1, 0xb1, 0x12, 0xc8, 0xa7,
	0x2c, 0x54, 0xb5, 0x3b, 0x5e, 0x3d, 0x31, 0x27, 0x61, 0x29, 0x4d, 0xad, 0x9c, 0xa6, 0x0d, 0xad,
	0x2b, 0x26, 0xa4, 0xa2, 0x49, 0x78, 0xf8, 0x7b, 0x85, 0x42, 0xd2, 0xf7, 0x40, 0x4c, 0xa7, 0x58,
	0xc6, 0x0b, 0x81, 0xe4, 0x0d, 0x38, 0x8a, 0x57, 0xd7, 0xea, 0x57, 0x07, 0x87, 0x97, 0xc7, 0xa3,
	0x8c, 0x78, 0x75, 0xd1, 0x5b, 0x47, 0xe9, 0x13, 0x9c, 0x5c, 0xc7, 0xfa, 0xb1, 0x06, 0xcc, 0xf9,
	0xb6, 0x76, 0xf0, 0x6d, 0x3f, 0xc3, 0x77, 0xb5, 0xc4, 0xb7, 0xd1, 0x6a, 0xcd, 0x6c, 0x95, 0x5e,
	0x40, 0xcb, 0xc8, 0xac, 0xab, 0x3e, 0x83, 0x3a, 0x47, 0xb1, 0x8a, 0xa4, 0xce, 0xad, 0x2d, 0x3a,
	0x84, 0x93, 0x9b, 0xfb, 0xf8, 0xb1, 0x50, 0xe6, 0x2b, 0x38, 0x50, 0x3d, 0x4c, 0x33, 0xba, 0x1b,
	0xca, 0x9e, 0x84, 0x74, 0x06, 0x2d, 0xe3, 0xfa, 0x26, 0x23, 0xd6, 0x6e, 0x46, 0xc8, 0x45, 0xd2,
	0xa7, 0x1a, 0xa5, 0x6b, 0x2b, 0xea, 0x5a, 0xf9, 0x45, 0x3d, 0x63, 0x2f, 0xbd, 0x41, 0x7f, 0x02,
	0x49, 0x9a, 0x48, 0xfd, 0x7b, 0x2b, 0x33, 0xe9, 0xb0, 0x0b, 0x93, 0x4f, 0x65, 0x52, 0xcd, 0x65,
	0x42, 0x87, 0xd0, 0x2e, 0xa0, 0xef, 0x21, 0x69, 0x0c, 0xe4, 0x33, 0x46, 0x28, 0xf1, 0x7f, 0x69,
	0x1a, 0x42, 0xbb, 0xf0, 0x60, 0x0f, 0xfe, 0x77, 0x68, 0x7b, 0x38, 0x63, 0x42, 0x22, 0xbf, 0x15,
	0xc8, 0xd3, 0x04, 0x04, 0x6a, 0x0b, 0x7f, 0x9e, 0xaa, 0x45, 0x9d, 0x13, 0x09, 0xe1, 0xdc, 0x67,
	0x51, 0xba, 0xb2, 0xca, 0x50, 0xbb, 0xa7, 0x36, 0x4a, 0x77, 0xa9, 0x2d, 0x3a, 0x82, 0x53, 0x0f,
	0x67, 0x82, 0x65, 0xc0, 0xcf, 0x17, 0x72, 0xf9, 0xb7, 0x0a, 0xc7, 0xd7, 0x7a, 0x26, 0x37, 0xc8,
	0x1f, 0x58, 0x80, 0x64, 0x02, 0x90, 0x6f, 0x01, 0xe9, 0xe6, 0x33, 0xdb, 0x58, 0x98, 0xce, 0xf9,
	0xf6, 0xe0, 0x3a, 0x29, 0xad, 0x90, 0x2f, 0xd0, 0xcc, 0x94, 0x49, 0x3a, 0xf9, 0xe5, 0xf2, 0xa2,
	0x74, 0xba, 0x5b, 0x63, 0x26, 0x4e, 0xa6, 0x42, 0x13, 0xa7, 0xac, 0x64, 0x13, 0x67, 0x43, 0xb6,
	0xb4, 0x42, 0xae, 0xe0, 0xd0, 0x90, 0x01, 0x39, 0x2f, 0x66, 0x2d, 0x6a, 0xaf, 0xd3, 0xdb, 0x11,
	0x35, 0xd1, 0x8c, 0xa1, 0x9b, 0x68, 0x9b, 0xe2, 0x31, 0xd1, 0xb6, 0x28, 0x85, 0x56, 0xc8, 0x57,
	0x38, 0x32, 0x35, 0x41, 0x8c, 0x07, 0x5b, 0xb4, 0xd2, 0x79, 0x5d, 0x08, 0x6f, 0x4c, 0x9c, 0x56,
	0x3e, 0x1e, 0xfd, 0x80, 0xfc, 0xb7, 0xb8, 0xab, 0xab, 0x5f, 0xe2, 0xdd, 0xbf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xe8, 0xd4, 0x43, 0xfd, 0x55, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PictweetServiceClient is the client API for PictweetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PictweetServiceClient interface {
	ListTweets(ctx context.Context, in *ListTweetsRequest, opts ...grpc.CallOption) (*ListTweetsResponse, error)
	PostTweet(ctx context.Context, in *PostTweetRequest, opts ...grpc.CallOption) (*PostTweetResponse, error)
	ShowTweet(ctx context.Context, in *ShowTweetRequest, opts ...grpc.CallOption) (*ShowTweetResponse, error)
	PostComment(ctx context.Context, in *PostCommentRequest, opts ...grpc.CallOption) (*PostCommentResponse, error)
	DeleteTweet(ctx context.Context, in *DeleteTweetRequest, opts ...grpc.CallOption) (*DeleteTweetResponse, error)
	RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegsiterUserResponse, error)
}

type pictweetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPictweetServiceClient(cc grpc.ClientConnInterface) PictweetServiceClient {
	return &pictweetServiceClient{cc}
}

func (c *pictweetServiceClient) ListTweets(ctx context.Context, in *ListTweetsRequest, opts ...grpc.CallOption) (*ListTweetsResponse, error) {
	out := new(ListTweetsResponse)
	err := c.cc.Invoke(ctx, "/pictweet.PictweetService/ListTweets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pictweetServiceClient) PostTweet(ctx context.Context, in *PostTweetRequest, opts ...grpc.CallOption) (*PostTweetResponse, error) {
	out := new(PostTweetResponse)
	err := c.cc.Invoke(ctx, "/pictweet.PictweetService/PostTweet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pictweetServiceClient) ShowTweet(ctx context.Context, in *ShowTweetRequest, opts ...grpc.CallOption) (*ShowTweetResponse, error) {
	out := new(ShowTweetResponse)
	err := c.cc.Invoke(ctx, "/pictweet.PictweetService/ShowTweet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pictweetServiceClient) PostComment(ctx context.Context, in *PostCommentRequest, opts ...grpc.CallOption) (*PostCommentResponse, error) {
	out := new(PostCommentResponse)
	err := c.cc.Invoke(ctx, "/pictweet.PictweetService/PostComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pictweetServiceClient) DeleteTweet(ctx context.Context, in *DeleteTweetRequest, opts ...grpc.CallOption) (*DeleteTweetResponse, error) {
	out := new(DeleteTweetResponse)
	err := c.cc.Invoke(ctx, "/pictweet.PictweetService/DeleteTweet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pictweetServiceClient) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegsiterUserResponse, error) {
	out := new(RegsiterUserResponse)
	err := c.cc.Invoke(ctx, "/pictweet.PictweetService/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PictweetServiceServer is the server API for PictweetService service.
type PictweetServiceServer interface {
	ListTweets(context.Context, *ListTweetsRequest) (*ListTweetsResponse, error)
	PostTweet(context.Context, *PostTweetRequest) (*PostTweetResponse, error)
	ShowTweet(context.Context, *ShowTweetRequest) (*ShowTweetResponse, error)
	PostComment(context.Context, *PostCommentRequest) (*PostCommentResponse, error)
	DeleteTweet(context.Context, *DeleteTweetRequest) (*DeleteTweetResponse, error)
	RegisterUser(context.Context, *RegisterUserRequest) (*RegsiterUserResponse, error)
}

// UnimplementedPictweetServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPictweetServiceServer struct {
}

func (*UnimplementedPictweetServiceServer) ListTweets(ctx context.Context, req *ListTweetsRequest) (*ListTweetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTweets not implemented")
}
func (*UnimplementedPictweetServiceServer) PostTweet(ctx context.Context, req *PostTweetRequest) (*PostTweetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostTweet not implemented")
}
func (*UnimplementedPictweetServiceServer) ShowTweet(ctx context.Context, req *ShowTweetRequest) (*ShowTweetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowTweet not implemented")
}
func (*UnimplementedPictweetServiceServer) PostComment(ctx context.Context, req *PostCommentRequest) (*PostCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostComment not implemented")
}
func (*UnimplementedPictweetServiceServer) DeleteTweet(ctx context.Context, req *DeleteTweetRequest) (*DeleteTweetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTweet not implemented")
}
func (*UnimplementedPictweetServiceServer) RegisterUser(ctx context.Context, req *RegisterUserRequest) (*RegsiterUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}

func RegisterPictweetServiceServer(s *grpc.Server, srv PictweetServiceServer) {
	s.RegisterService(&_PictweetService_serviceDesc, srv)
}

func _PictweetService_ListTweets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTweetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PictweetServiceServer).ListTweets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pictweet.PictweetService/ListTweets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PictweetServiceServer).ListTweets(ctx, req.(*ListTweetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PictweetService_PostTweet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostTweetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PictweetServiceServer).PostTweet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pictweet.PictweetService/PostTweet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PictweetServiceServer).PostTweet(ctx, req.(*PostTweetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PictweetService_ShowTweet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowTweetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PictweetServiceServer).ShowTweet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pictweet.PictweetService/ShowTweet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PictweetServiceServer).ShowTweet(ctx, req.(*ShowTweetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PictweetService_PostComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PictweetServiceServer).PostComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pictweet.PictweetService/PostComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PictweetServiceServer).PostComment(ctx, req.(*PostCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PictweetService_DeleteTweet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTweetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PictweetServiceServer).DeleteTweet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pictweet.PictweetService/DeleteTweet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PictweetServiceServer).DeleteTweet(ctx, req.(*DeleteTweetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PictweetService_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PictweetServiceServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pictweet.PictweetService/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PictweetServiceServer).RegisterUser(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PictweetService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pictweet.PictweetService",
	HandlerType: (*PictweetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTweets",
			Handler:    _PictweetService_ListTweets_Handler,
		},
		{
			MethodName: "PostTweet",
			Handler:    _PictweetService_PostTweet_Handler,
		},
		{
			MethodName: "ShowTweet",
			Handler:    _PictweetService_ShowTweet_Handler,
		},
		{
			MethodName: "PostComment",
			Handler:    _PictweetService_PostComment_Handler,
		},
		{
			MethodName: "DeleteTweet",
			Handler:    _PictweetService_DeleteTweet_Handler,
		},
		{
			MethodName: "RegisterUser",
			Handler:    _PictweetService_RegisterUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/interfaces/rpc/pictweetpb/pictweet.proto",
}
